import React, { useState } from "react";
import ReactApexChart from "react-apexcharts";
import "../styles/XScore.css";
import { PiXLogoLight } from "react-icons/pi";

const XScore = () => {
  const [options] = useState({
    chart: {
      height: 350,
      type: "radialBar",
      toolbar: {
        show: false,
      },
    },
    plotOptions: {
      radialBar: {
        startAngle: -115,
        endAngle: 115,
        hollow: {
          margin: 0,
          size: "75%",
          image: undefined,
          imageOffsetX: 0,
          imageOffsetY: 0,
          position: "front",
          dropShadow: {
            enabled: true,
            top: 3,
            left: 0,
            blur: 4,
            opacity: 0.24,
          },
        },
        track: {
          background: "#1C1C1C",
          strokeWidth: "100%",
          margin: 0,
          dropShadow: {
            enabled: true,
            top: -3,
            left: 0,
            blur: 4,
            opacity: 0.95,
          },
        },
        dataLabels: {
          show: true,
          name: {
            offsetY: -10,
            show: true,
            fontSize: "16px",
            fontWeight: "400",
            color: "rgba(255, 255, 255, 0.7)",
          },
          value: {
            formatter(val) {
              return parseInt((1000 * val) / 100);
            },
            color: "#fff",
            fontSize: "36px",
            show: true,
          },
        },
      },
    },
    fill: {
      type: "gradient",
      gradient: {
        shade: "dark",
        type: "horizontal",
        shadeIntensity: 1,
        gradientToColors: ["#ACFD00"],
        inverseColors: false,
        opacityFrom: 1,
        opacityTo: 1,
        stops: [0, 100],
      },
    },
    stroke: {
      lineCap: "round",
    },
    labels: ["Excellent"],
  });

  const [series] = useState([86]);

  return (
    <div className="chart-container">
      <div className="text-info">
        <div className="text-header">X Score</div>
        <p>
          Score generated by inspect.xyz based on the popularity of this account
          in crypto space
        </p>
      </div>
      <div id="card">
        <div id="chart">
          <ReactApexChart
            options={options}
            series={series}
            type="radialBar"
            height={350}
          />
        </div>
        <div className="chart-range">
          <p>0</p>
          <p>1000</p>
        </div>
        <button className="custom-button">
          <PiXLogoLight />
          <span>&nbsp;&nbsp;Share</span>
        </button>
      </div>
    </div>
  );
};

export default XScore;
