import React from "react";
import Tabs from "./Navigation";
import "../styles/XScore.css";

const XScore = () => {
  return (
    <div className="xscore">
      <Tabs />
      <h3>X Score</h3>
      <div className="score">
        <p>860</p>
        <p>Excellent</p>
      </div>
      <button>Share</button>
      <p>
        Score generated by inspect.xyz based on the popularity of this account
        in crypto space
      </p>
    </div>
  );
};

export default XScore;
